language: node_js

node_js:
  - "10"

sudo: false

cache:
  directories:
    - "node_modules"

deploy:
  provider: npm
  skip-cleanup: true
  email: $NPM_EMAIL
  api_key: $NPM_TOKEN
  script:
    - npm run build
  on:
    tags: true
    repo: cns-iu/pdfkit-browserify
