language: node_js

node_js:
  - "10"

sudo: false

cache:
  directories:
    - "node_modules"

script:
  - npm run build

deploy:
  provider: npm
  skip-cleanup: true
  email: $NPM_EMAIL
  api_key: $NPM_TOKEN
  on:
    tags: true
    repo: cns-iu/pdfkit-browserify
